/*
 * TronIDE — GitHub OAuth code→token exchange (Deno Deploy).
 *
 * The IDE is a static site on GitHub Pages, so it cannot hold the OAuth client
 * secret or call GitHub's token endpoint (no CORS) itself. This single-file
 * Deno function is the only server-side piece: it receives the `code` from the
 * GitHub authorization popup, exchanges it (with the secret) for an access
 * token, resolves the login, and hands both back to the opener via postMessage.
 *
 * Deploy:  deployctl deploy --project=tronide-gh-oauth main.ts
 * Callback (register in the GitHub OAuth App):
 *          https://tronide-gh-oauth.redchar1992.deno.net/callback
 *
 * Env vars (Deno Deploy → Settings → Environment Variables):
 *   GITHUB_CLIENT_ID       the OAuth App client id
 *   GITHUB_CLIENT_SECRET   the OAuth App client secret   (never shipped to the browser)
 *   REDIRECT_URI           https://tronide-gh-oauth.redchar1992.deno.net/callback
 *   ALLOWED_ORIGINS        comma-separated site origins allowed to receive the token,
 *                          e.g. "https://tronide.io,https://<user>.github.io"
 */

const CLIENT_ID = Deno.env.get('GITHUB_CLIENT_ID') ?? ''
const CLIENT_SECRET = Deno.env.get('GITHUB_CLIENT_SECRET') ?? ''
const REDIRECT_URI = Deno.env.get('REDIRECT_URI') ?? 'https://tronide-gh-oauth.redchar1992.deno.net/callback'
const ALLOWED_ORIGINS = (Deno.env.get('ALLOWED_ORIGINS') ?? 'https://tronide.io')
  .split(',').map((s) => s.trim()).filter(Boolean)

// Neutralize sequences that can break out of a <script> context. JSON.stringify
// does NOT escape `</script>`, `-->`, or the JS line terminators U+2028/U+2029,
// so a reflected value (state / GitHub error) could otherwise inject markup.
function escapeForScript (json: string): string {
  return json
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029')
}

// `state` is generated by the browser as hex and only echoed back; reject
// anything else so a crafted value can never be reflected into the page.
function safeState (raw: string | null): string {
  return raw && /^[A-Za-z0-9]{8,64}$/.test(raw) ? raw : ''
}

// Render a tiny page that posts the result to the opener and closes itself.
// We post to EACH allowed origin: the browser only delivers a message when the
// opener's origin matches the targetOrigin, so looping never leaks the token to
// an unintended origin.
function resultPage (payload: Record<string, unknown>): Response {
  const data = escapeForScript(JSON.stringify({ source: 'tronide-github-oauth', ...payload }))
  const origins = escapeForScript(JSON.stringify(ALLOWED_ORIGINS))
  const body = `<!doctype html><html><head><meta charset="utf-8"><title>GitHub</title></head>
<body style="font:14px system-ui;padding:24px;color:#333">
<script>
(function () {
  var data = ${data};
  var origins = ${origins};
  try {
    if (window.opener) origins.forEach(function (o) { try { window.opener.postMessage(data, o) } catch (e) {} });
  } catch (e) {}
  document.body.textContent = data.error
    ? ('GitHub connect failed: ' + data.error + '. You can close this window.')
    : 'GitHub connected. You can close this window.';
  setTimeout(function () { try { window.close() } catch (e) {} }, 300);
})();
</script>
<noscript>Enable JavaScript to finish connecting to GitHub.</noscript>
</body></html>`
  return new Response(body, {
    headers: {
      'content-type': 'text/html; charset=utf-8',
      'cache-control': 'no-store',
      'content-security-policy': "default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'"
    }
  })
}

Deno.serve(async (req: Request) => {
  const url = new URL(req.url)

  if (url.pathname === '/' || url.pathname === '/health') {
    return new Response('tronide-gh-oauth: ok', { headers: { 'cache-control': 'no-store' } })
  }
  if (url.pathname !== '/callback') return new Response('Not found', { status: 404 })

  const state = safeState(url.searchParams.get('state'))
  const oauthError = url.searchParams.get('error')
  if (oauthError) return resultPage({ state, error: oauthError })

  const code = url.searchParams.get('code')
  if (!code) return resultPage({ state, error: 'missing_code' })
  if (!CLIENT_ID || !CLIENT_SECRET) return resultPage({ state, error: 'server_misconfigured' })

  // Exchange the code for an access token (secret stays here).
  let token = ''
  try {
    const res = await fetch('https://github.com/login/oauth/access_token', {
      method: 'POST',
      headers: { Accept: 'application/json', 'Content-Type': 'application/json' },
      body: JSON.stringify({ client_id: CLIENT_ID, client_secret: CLIENT_SECRET, code, redirect_uri: REDIRECT_URI })
    })
    const data = await res.json()
    token = data.access_token ?? ''
    if (!token) return resultPage({ state, error: data.error_description || data.error || 'exchange_failed' })
  } catch (_e) {
    return resultPage({ state, error: 'exchange_request_failed' })
  }

  // Resolve the login server-side (no browser CORS to api.github.com needed).
  let login = ''
  try {
    const ures = await fetch('https://api.github.com/user', {
      headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json', 'User-Agent': 'tronide-gh-oauth' }
    })
    if (ures.ok) login = (await ures.json()).login ?? ''
  } catch (_e) { /* login is best-effort; the token still works */ }

  return resultPage({ state, token, login })
})
